name: Contributor Helper

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-cool/contributor-helper@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-files: 'README.md, README_zh.md'
          update-places: '<!--contributor-start-->/<!--contributor-end-->'
          block-users: 'dependabot[bot],dependabot-preview[bot]'
          style: 'simple'
          avatar-width: '48'

      - name: Commit and push if changed üìù
        run: |-
          git diff
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git pull
          git add -A
          git commit -m "docs: update contributors" || exit 0
          git push
